package com.github.daanbouwman.flightplanner.core.database.airport

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * An airport in the shipped, read-only database.
 *
 * Generated by `:tools:airportdb` from the OurAirports public-domain dataset.
 * The four trailing columns are denormalised at build time because they are
 * read on every route generation and joining to `runways` for them would be the
 * single hottest query in the app.
 */
@Entity(
    tableName = "airports",
    indices = [
        Index(value = ["icao"], unique = true),
        Index(value = ["longest_runway_ft"]),
        Index(value = ["lat"]),
        Index(value = ["size_class"]),
    ],
)
data class AirportEntity(
    @PrimaryKey
    @ColumnInfo(name = "id")
    val id: Int,

    @ColumnInfo(name = "icao")
    val icao: String,

    /**
     * 1 when [icao] is a real ICAO code, 0 when it came from the OurAirports
     * `ident` column. Flight-planning tools only accept real ICAO codes, so this
     * backs the "ICAO airports only" preference.
     */
    @ColumnInfo(name = "has_icao")
    val hasIcao: Boolean,

    @ColumnInfo(name = "ident")
    val ident: String,

    @ColumnInfo(name = "name")
    val name: String,

    @ColumnInfo(name = "lat")
    val lat: Double,

    @ColumnInfo(name = "lon")
    val lon: Double,

    @ColumnInfo(name = "elevation_ft")
    val elevationFt: Int,

    @ColumnInfo(name = "country")
    val country: String,

    @ColumnInfo(name = "municipality")
    val municipality: String?,

    /** 0 = small, 1 = medium, 2 = large. */
    @ColumnInfo(name = "size_class")
    val sizeClass: Int,

    @ColumnInfo(name = "scheduled_service")
    val scheduledService: Boolean,

    // --- denormalised at build time; see the ETL ---

    @ColumnInfo(name = "longest_runway_ft")
    val longestRunwayFt: Int,

    @ColumnInfo(name = "runway_count")
    val runwayCount: Int,

    @ColumnInfo(name = "has_hard_surface")
    val hasHardSurface: Boolean,

    @ColumnInfo(name = "has_lighting")
    val hasLighting: Boolean,
)
