package com.github.daanbouwman.flightplanner.core.database.airport

import androidx.room.Database
import androidx.room.RoomDatabase

/**
 * The shipped, read-only airport database.
 *
 * Never migrated. It is derived data, generated by `:tools:airportdb` from the
 * OurAirports public-domain dataset, so a refresh is a version bump plus a new
 * asset and the old file is simply dropped. That is why it is kept separate
 * from the user database: replacing this one must never be able to endanger a
 * user's logbook.
 *
 * The asset is produced from this class's *exported schema JSON*, including the
 * `room_master_table` identity hash. If the two ever drift, Room fails to open
 * the database on first launch — on every device. `verifyAirportAsset` guards
 * against that at build time.
 */
@Database(
    entities = [AirportEntity::class, RunwayEntity::class, DatasetMetaEntity::class],
    version = AirportDatabase.VERSION,
    exportSchema = true,
)
abstract class AirportDatabase : RoomDatabase() {

    abstract fun airportDao(): AirportDao

    abstract fun runwayDao(): RunwayDao

    abstract fun datasetMetaDao(): DatasetMetaDao

    companion object {
        const val VERSION = 1
        const val NAME = "airports.db"
        const val ASSET_PATH = "databases/airports.db"

        /** Sidecar holding the schema identity hash; see [AirportAssetInstaller]. */
        const val ASSET_VERSION_PATH = "databases/airports.db.version"
    }
}
