// Generates everything in the mirror that is derived rather than authored:
//
//   src/tokens/tokens.gen.ts   typed access to the exported Kotlin values
//   dist/styles.css            the CSS custom properties + every component stylesheet
//
// tokens.json itself is written by :core:designsystem's DesignTokenExport — see
// DesignTokenExportTest. Nothing here invents a value; it only reshapes them.

import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs'
import { join, dirname, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const tokens = JSON.parse(readFileSync(join(here, 'src/tokens/tokens.json'), 'utf8'))

/**
 * `surfaceContainerHigh` -> `surface-container-high`, `sock.alternateBand` ->
 * `sock-alternate-band`.
 *
 * The sky palette's keys are dotted paths (`day.cloudEdge`), and a dot is not a
 * legal character in a CSS custom property name — it silently produces a variable
 * nothing can ever resolve.
 */
const kebab = (s) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/\./g, '-')
    .toLowerCase()

// ---------------------------------------------------------------------------
// Springs
//
// Compose animates with a real spring, so the honest translation of a motion
// token is the spring's own response curve rather than a cubic-bezier that
// looks vaguely similar. CSS `linear()` takes an arbitrary sampled curve, which
// is exactly what a damped oscillator produces — including the overshoot that
// IS the expressive character of a spatial spring (see DESIGN-SYSTEM.md: "a
// card that moves reads as having mass"). An underdamped spring cannot be
// expressed as a cubic-bezier at all: a bezier is monotone in the range a
// transition uses, and the overshoot is the part that would be lost.
//
// Unit mass, matching androidx.compose.animation.core.SpringSpec.
// ---------------------------------------------------------------------------

/** Position of a unit step response at time `t` seconds, starting at 0, target 1. */
function springAt(t, dampingRatio, stiffness) {
  const wn = Math.sqrt(stiffness)
  const z = dampingRatio
  if (z < 1) {
    const wd = wn * Math.sqrt(1 - z * z)
    return (
      1 -
      Math.exp(-z * wn * t) * (Math.cos(wd * t) + ((z * wn) / wd) * Math.sin(wd * t))
    )
  }
  if (z === 1) return 1 - Math.exp(-wn * t) * (1 + wn * t)
  const r1 = -wn * (z - Math.sqrt(z * z - 1))
  const r2 = -wn * (z + Math.sqrt(z * z - 1))
  return 1 - (r1 * Math.exp(r2 * t) - r2 * Math.exp(r1 * t)) / (r1 - r2)
}

/**
 * How long the spring takes to settle, in seconds.
 *
 * Compose stops at its visibility threshold rather than at infinity; 1/1000 of
 * the travel is the threshold Compose uses for a unitless float.
 */
function settleTime(dampingRatio, stiffness) {
  const dt = 1 / 1000
  const threshold = 0.001
  let lastMoving = 0
  for (let i = 1; i <= 10000; i++) {
    const t = i * dt
    if (Math.abs(springAt(t, dampingRatio, stiffness) - 1) > threshold) lastMoving = t
    if (t - lastMoving > 0.05) break
  }
  return Math.max(lastMoving + 1 / 60, 0.05)
}

/** A CSS `linear()` easing sampling the spring's own response. */
function springEasing(dampingRatio, stiffness, samples = 48) {
  const duration = settleTime(dampingRatio, stiffness)
  const points = []
  for (let i = 0; i <= samples; i++) {
    const v = springAt((i / samples) * duration, dampingRatio, stiffness)
    points.push(Number(v.toFixed(4)))
  }
  points[points.length - 1] = 1
  return { easing: `linear(${points.join(', ')})`, durationMs: Math.round(duration * 1000) }
}

// ---------------------------------------------------------------------------
// tokens.gen.ts
// ---------------------------------------------------------------------------

const motionDerived = {}
for (const [name, spec] of Object.entries(tokens.motion)) {
  motionDerived[name] = { ...spec, ...springEasing(spec.dampingRatio, spec.stiffness) }
}

const generated = `// GENERATED by design-mirror/build.mjs from src/tokens/tokens.json.
// Do not edit. tokens.json itself is generated from :core:designsystem.

export const tokens = ${JSON.stringify({ ...tokens, motion: motionDerived }, null, 2)} as const

export type SchemeName = keyof typeof tokens.schemes
export type ColorRole = keyof typeof tokens.schemes.brandLight
export type TypeSlot = keyof typeof tokens.typography
export type ShapeSize = keyof typeof tokens.shapes
export type MotionToken = keyof typeof tokens.motion
export type SkyKey = keyof typeof tokens.sky.brandLight
export type FlightRulesKey = keyof typeof tokens.flightRules.light
`
mkdirSync(join(here, 'src/tokens'), { recursive: true })
writeFileSync(join(here, 'src/tokens/tokens.gen.ts'), generated)

// ---------------------------------------------------------------------------
// dist/styles.css
// ---------------------------------------------------------------------------

const lines = []
lines.push('/* GENERATED by design-mirror/build.mjs. Values come from :core:designsystem. */')
lines.push('')

/** The variables one colour scheme defines. */
function schemeVars(scheme, indent) {
  const out = []
  for (const [role, hex] of Object.entries(tokens.schemes[scheme])) {
    out.push(`${indent}--fp-${kebab(role)}: ${hex};`)
  }
  for (const [key, hex] of Object.entries(tokens.sky[scheme])) {
    out.push(`${indent}--fp-sky-${kebab(key)}: ${hex};`)
  }
  // Cockpit is a dark theme and Chart a light one, so each takes the flight-rules
  // mapping for its own tone — never one of its own. Those colours are safety
  // data: a night theme may restyle the app, it may not restate the weather.
  const tone = scheme === 'brandDark' || scheme === 'cockpit' ? 'dark' : 'light'
  for (const [cat, pair] of Object.entries(tokens.flightRules[tone])) {
    out.push(`${indent}--fp-${cat}-container: ${pair.container};`)
    out.push(`${indent}--fp-${cat}-on-container: ${pair.onContainer};`)
  }
  out.push(`${indent}color-scheme: ${tone === 'dark' ? 'dark' : 'light'};`)
  return out
}

// Theme-invariant tokens: shape, type and motion do not vary by scheme.
lines.push(':root, [data-fp-theme] {')
for (const [name, dp] of Object.entries(tokens.shapes)) {
  lines.push(`  --fp-shape-${kebab(name)}: ${dp}px;`)
}
for (const [name, m] of Object.entries(motionDerived)) {
  lines.push(`  --fp-motion-${kebab(name)}-duration: ${m.durationMs}ms;`)
  lines.push(`  --fp-motion-${kebab(name)}-easing: ${m.easing};`)
}
lines.push(`  --fp-stagger: ${tokens.constants.enterStaggerMillis}ms;`)
lines.push('}')
lines.push('')

// The brand light scheme is the default, so a page that forgets the provider is
// still on-brand rather than unstyled.
lines.push(':root {')
lines.push(...schemeVars('brandLight', '  '))
lines.push('}')
lines.push('')
for (const scheme of Object.keys(tokens.schemes)) {
  lines.push(`[data-fp-theme="${kebab(scheme)}"] {`)
  lines.push(...schemeVars(scheme, '  '))
  lines.push('}')
  lines.push('')
}

// `system` is resolved here rather than from matchMedia in the provider, so a
// design paints the right scheme on the first frame instead of correcting itself
// after mount.
lines.push('[data-fp-theme="system"] {')
lines.push(...schemeVars('brandLight', '  '))
lines.push('}')
lines.push('')
lines.push('@media (prefers-color-scheme: dark) {')
lines.push('  [data-fp-theme="system"] {')
lines.push(...schemeVars('brandDark', '    '))
lines.push('  }')
lines.push('}')
lines.push('')

// Type scale, as classes. A slot is a class rather than a set of variables
// because a caller wants "this is titleMedium", not four separate decisions.
for (const [slot, s] of Object.entries(tokens.typography)) {
  const decls = [
    `  font-size: ${s.fontSize}px;`,
    `  line-height: ${s.lineHeight}px;`,
    `  letter-spacing: ${s.letterSpacing}px;`,
    `  font-weight: ${s.fontWeight ?? 400};`,
  ]
  // "tnum" is what keeps a column of distances from twitching as its digits change.
  if (s.fontFeatureSettings) decls.push(`  font-feature-settings: "${s.fontFeatureSettings}";`)
  decls.push(`  font-variant-numeric: ${s.fontFeatureSettings === 'tnum' ? 'tabular-nums' : 'normal'};`)
  lines.push(`.fp-type-${kebab(slot)} {`)
  lines.push(...decls)
  lines.push('}')
}
lines.push('')

// Every component stylesheet, inlined in a stable order.
const cssDir = join(here, 'src')
function collectCss(dir, acc = []) {
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) collectCss(p, acc)
    else if (name.endsWith('.css')) acc.push(p)
  }
  return acc
}
for (const file of collectCss(cssDir)) {
  lines.push(`/* ${relative(here, file).replace(/\\/g, '/')} */`)
  lines.push(readFileSync(file, 'utf8').trim())
  lines.push('')
}

mkdirSync(join(here, 'dist'), { recursive: true })
writeFileSync(join(here, 'dist/styles.css'), lines.join('\n'))

console.log(
  `design-mirror: wrote src/tokens/tokens.gen.ts and dist/styles.css ` +
    `(${Object.keys(tokens.schemes).length} schemes, ${Object.keys(tokens.typography).length} type slots)`,
)

// ---------------------------------------------------------------------------
// The world outline
//
// Decoded from the app's own `land.outline` asset — the same bytes the phone
// reads — so the mirror's coastline cannot drift from the app's. The format is
// WorldOutlineCodec in :core:routing: a 16-byte header, a ring table of int32
// offsets, then two int16 coordinate columns quantised onto the signed 16-bit
// range. Re-emitted as base64 because it is 19 KB of binary and JSON would
// quadruple it for no gain.
// ---------------------------------------------------------------------------

const OUTLINE_MAGIC = 0x4650574d
const LON_SCALE = 32767 / 180
const LAT_SCALE = 32767 / 90

const outlinePath = join(here, '../app/src/main/assets/maps/land.outline')
const raw = readFileSync(outlinePath)
const view = new DataView(raw.buffer, raw.byteOffset, raw.byteLength)

if (view.getInt32(0, true) !== OUTLINE_MAGIC) {
  throw new Error(`${outlinePath} is not a world outline blob`)
}
const outlineVersion = view.getInt32(4, true)
if (outlineVersion !== 1) {
  throw new Error(`World outline blob is version ${outlineVersion}, expected 1`)
}
const ringCount = view.getInt32(8, true)
const pointCount = view.getInt32(12, true)
const expectedBytes = 16 + (ringCount + 1) * 4 + pointCount * 2 * 2
if (raw.byteLength !== expectedBytes) {
  throw new Error(
    `World outline blob is ${raw.byteLength} bytes, expected ${expectedBytes} ` +
      `for ${ringCount} rings and ${pointCount} points`,
  )
}

// Per-ring bounding boxes, so projectOutline rejects a ring in four comparisons
// rather than a thousand projections. Precomputed here rather than in the browser
// because it is the same answer every time.
const ringStart = []
for (let i = 0; i <= ringCount; i++) ringStart.push(view.getInt32(16 + i * 4, true))
const coordBase = 16 + (ringCount + 1) * 4
const lonAt = (i) => view.getInt16(coordBase + i * 2, true) / LON_SCALE
const latAt = (i) => view.getInt16(coordBase + (pointCount + i) * 2, true) / LAT_SCALE

const boxes = { minLon: [], maxLon: [], minLat: [], maxLat: [] }
for (let ring = 0; ring < ringCount; ring++) {
  let minLon = Infinity
  let maxLon = -Infinity
  let minLat = Infinity
  let maxLat = -Infinity
  for (let i = ringStart[ring]; i < ringStart[ring + 1]; i++) {
    const lo = lonAt(i)
    const la = latAt(i)
    if (lo < minLon) minLon = lo
    if (lo > maxLon) maxLon = lo
    if (la < minLat) minLat = la
    if (la > maxLat) maxLat = la
  }
  boxes.minLon.push(minLon)
  boxes.maxLon.push(maxLon)
  boxes.minLat.push(minLat)
  boxes.maxLat.push(maxLat)
}

const round4 = (v) => Number(v.toFixed(4))
writeFileSync(
  join(here, 'src/geo/worldOutline.gen.ts'),
  `// GENERATED by design-mirror/build.mjs from app/src/main/assets/maps/land.outline.
// Do not edit. Same bytes the phone reads, so the coastline cannot drift.

import type { WorldOutline } from './mapFrame'

const BLOB =
  '${raw.toString('base64')}'

const RING_MIN_LON = ${JSON.stringify(boxes.minLon.map(round4))}
const RING_MAX_LON = ${JSON.stringify(boxes.maxLon.map(round4))}
const RING_MIN_LAT = ${JSON.stringify(boxes.minLat.map(round4))}
const RING_MAX_LAT = ${JSON.stringify(boxes.maxLat.map(round4))}

const RING_COUNT = ${ringCount}
const POINT_COUNT = ${pointCount}
const LON_SCALE = 32767 / 180
const LAT_SCALE = 32767 / 90

const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

/** Self-contained, so the module needs neither atob nor Node's Buffer. */
function decodeBase64(input: string): Uint8Array {
  const clean = input.replace(/=+$/, '')
  const bytes = new Uint8Array((clean.length * 3) >> 2)
  let acc = 0
  let bits = 0
  let out = 0
  for (let i = 0; i < clean.length; i++) {
    acc = (acc << 6) | B64.indexOf(clean[i])
    bits += 6
    if (bits >= 8) {
      bits -= 8
      bytes[out++] = (acc >> bits) & 0xff
    }
  }
  return bytes
}

let cached: WorldOutline | null = null

/**
 * The world's land polygons — 122 rings, simplified for a card-sized map.
 *
 * Rings are closed and a polygon's interior rings (the Caspian, the Great Lakes)
 * follow its exterior one unmarked, because filling with an **even-odd** rule
 * makes an enclosed ring a hole for free. A non-zero rule fills lakes as land.
 */
export function worldOutline(): WorldOutline {
  if (cached) return cached
  const bytes = decodeBase64(BLOB)
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength)
  const coordBase = 16 + (RING_COUNT + 1) * 4

  const ringStart = new Int32Array(RING_COUNT + 1)
  for (let i = 0; i <= RING_COUNT; i++) ringStart[i] = view.getInt32(16 + i * 4, true)

  const lon = new Float32Array(POINT_COUNT)
  const lat = new Float32Array(POINT_COUNT)
  for (let i = 0; i < POINT_COUNT; i++) {
    lon[i] = view.getInt16(coordBase + i * 2, true) / LON_SCALE
    lat[i] = view.getInt16(coordBase + (POINT_COUNT + i) * 2, true) / LAT_SCALE
  }

  cached = {
    lon,
    lat,
    ringStart,
    ringMinLon: Float32Array.from(RING_MIN_LON),
    ringMaxLon: Float32Array.from(RING_MAX_LON),
    ringMinLat: Float32Array.from(RING_MIN_LAT),
    ringMaxLat: Float32Array.from(RING_MAX_LAT),
  }
  return cached
}
`,
)

console.log(`design-mirror: wrote src/geo/worldOutline.gen.ts (${ringCount} rings, ${pointCount} points)`)
