// Fetches the Latin subsets of Roboto and Roboto Mono into `fonts/`.
//
// The Android app sets `FontFamily.SansSerif`, which on Android resolves to
// Roboto. Without shipping it, every design built with this mirror renders in
// whatever sans the viewer's browser defaults to — different metrics, so
// different line lengths, different wrapping and different truncation from the
// app it is supposed to mirror. Since "the airport name truncated to
// 'Stangland A…'" is a real design decision in this system, those metrics matter.
//
// Roboto and Roboto Mono are Apache-2.0, so shipping them is permitted; see
// THIRD-PARTY-NOTICES.md.
//
// Run: node fetch-fonts.mjs

import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const fontsDir = join(here, 'fonts')
mkdirSync(fontsDir, { recursive: true })

// A modern browser UA, or Google serves TTF instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&family=Roboto+Mono:wght@400&display=swap'

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

// Google emits one @font-face per unicode subset, each preceded by a comment
// naming it. Only Latin is kept: the app's UI strings are Latin, and the other
// eight subsets would quadruple the payload for glyphs no design will use.
const blocks = css.split('/*').slice(1)
const wanted = []
for (const block of blocks) {
  const subset = block.slice(0, block.indexOf('*/')).trim()
  if (subset !== 'latin') continue
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1]
  const weight = /font-weight:\s*(\d+)/.exec(block)?.[1]
  const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1]
  if (family && url) wanted.push({ family, weight: weight ?? '400', url })
}

if (wanted.length === 0) throw new Error('No latin subsets found in the Google Fonts response')

const seen = new Map()
const faces = []
for (const face of wanted) {
  const slug = `${face.family.toLowerCase().replace(/\s+/g, '-')}-${face.weight}`
  const file = `${slug}.woff2`
  if (!seen.has(face.url)) {
    const bytes = new Uint8Array(await (await fetch(face.url, { headers: { 'User-Agent': UA } })).arrayBuffer())
    writeFileSync(join(fontsDir, file), bytes)
    seen.set(face.url, file)
    console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)} KB`)
  }
  faces.push(
    `@font-face {\n` +
      `  font-family: '${face.family}';\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${face.weight};\n` +
      `  font-display: swap;\n` +
      `  src: url('./${seen.get(face.url)}') format('woff2');\n` +
      `}`,
  )
}

writeFileSync(
  join(fontsDir, 'fonts.css'),
  `/* GENERATED by design-mirror/fetch-fonts.mjs. Roboto and Roboto Mono, Apache-2.0.\n` +
    `   The app renders in Roboto because Compose's FontFamily.SansSerif resolves to it\n` +
    `   on Android; shipping it is what keeps the mirror's text metrics honest. */\n\n` +
    faces.join('\n\n') +
    '\n',
)

console.log(`design-mirror: wrote fonts/fonts.css with ${faces.length} face(s)`)
